port 53
proto tcp-server
dev tun
ca /home/ubuntu/openvpn/ca.crt
cert /home/ubuntu/openvpn/server.crt
key /home/ubuntu/openvpn/server.key
dh none
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist /tmp/ipp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
mtu-disc no
tun-mtu 1200
tun-mtu-extra 32
mssfix 1300
keepalive 10 60
persist-key
persist-tun
compress lz4-v2
verb 3